-- return {
-- {
-- 	"echasnovski/mini.misc",
-- 	version = false,
-- 	event = "VeryLazy",
-- 	config = function()
-- 		require("mini.misc").setup_auto_root({ "package.json", ".git" })
-- 	end,
-- },
-- {
-- 	"echasnovski/mini.statusline",
-- 	version = false,
-- 	event = "VeryLazy",
-- 	config = {
-- 		-- Content of statusline as functions which return statusline string. See
-- 		-- `:h statusline` and code of default contents (used instead of `nil`).
-- 		content = {
-- 			-- Content for active window
-- 			active = nil,
-- 			-- Content for inactive window(s)
-- 			inactive = nil,
-- 		},
--
-- 		-- Whether to use icons by default
-- 		use_icons = true,
--
-- 		-- Whether to set Vim's settings for statusline (make it always shown)
-- 		set_vim_settings = true,
-- 	},
-- },
-- }
