return {
	"stevearc/conform.nvim",
	event = { "BufWritePre" },
	opts = {
		formatters_by_ft = {
			lua = { "stylua" },
			javascript = { "prettierd" },
			typescript = { "prettierd" },
			javascriptreact = { "prettierd" },
			typescriptreact = { "prettierd" },
			bash = { "shfmt" },
			sh = { "shfmt" },
			html = { "prettierd" },
			css = { "prettierd" },
			scss = { "prettierd" },
			json = { "prettierd" },
			jsonc = { "prettierd" },
			yaml = { "prettierd" },
			markdown = { "prettierd" },
			graphql = { "prettierd" },
			toml = { "taplo" },
			svelte = { "prettierd" },
			svx = { "prettierd" },
		},
		format_on_save = {
			lsp_fallback = false,
			async = false,
			timeout_ms = 500,
		},
	},
}
