local g = vim.g
g.zipPlugin = false -- disable zip
g.load_black = false -- disable black
g.loaded_2html_plugin = true -- disable 2html
g.loaded_getscript = true -- disable getscript
g.loaded_getscriptPlugin = true -- disable getscript
g.loaded_gzip = true -- disable gzip
g.loaded_logipat = true -- disable logipat
g.loaded_matchit = true -- disable matchit
g.loaded_netrwFileHandlers = true -- disable netrw
g.loaded_netrwPlugin = true -- disable netrw
g.loaded_netrwSettngs = true -- disable netrw
g.loaded_remote_plugins = true -- disable remote plugins
g.loaded_tar = true -- disable tar
g.loaded_tarPlugin = true -- disable tar
g.loaded_zip = true -- disable zip
g.loaded_zipPlugin = true -- disable zip
g.loaded_vimball = true -- disable vimball
g.loaded_vimballPlugin = true -- disable vimball
